import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router"
import { initailValues } from "../App";

const Page2 = () => {
  const [name, setName] = useState('')
  const { id } = useParams()
  const navigate = useNavigate()

  useEffect(() => {
    if (id) {
      const user = initailValues.find(item => item.id === +id)
      setName(user.name)
    }
  }, [id])

  if (id) {
    return (
      <div>
        <h1 onClick={() => navigate('/')}>{name}</h1>
      </div>
    )
  }

  return (
    <div>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Architecto id animi, sapiente enim, perspiciatis dolorem atque, ipsam facilis necessitatibus ratione explicabo impedit dolore ea? Consectetur asperiores iure cumque quasi id voluptatibus, tenetur quaerat, harum officia cum, voluptates reiciendis rerum numquam.</p>
      <p>Corrupti, voluptates! Temporibus dolor, reprehenderit ipsam fugiat libero dolore placeat ipsa. Magnam a sint est illum optio. Enim recusandae eveniet, ab aliquam est deserunt sapiente nulla esse quod distinctio, consectetur quibusdam. Vero a veniam reprehenderit quam, inventore minus delectus est.</p>
      <p>Quod eligendi officia soluta beatae earum quaerat neque officiis odit. Ea tempore nulla vero recusandae eveniet incidunt totam rem quae voluptate, temporibus accusamus inventore laborum architecto voluptatibus facere fugit cupiditate natus, officia commodi eius non deleniti quasi minima placeat. Itaque?</p>
      <p>Sit id dignissimos natus, cumque sint numquam officia illum consectetur vero in doloribus similique repellat quam deleniti sequi, dolorem quidem, error repudiandae vel quas debitis rerum quae aut. Ab similique, facilis voluptatum quam rem voluptatibus culpa nisi incidunt quas ut.</p>
      <p>Sapiente sint vel eveniet? Ipsam itaque eius necessitatibus expedita commodi quia veniam ipsum sunt delectus, possimus, ut dolore distinctio vitae reiciendis nulla libero blanditiis quisquam beatae cupiditate quod voluptate. Vitae neque magni doloremque iste praesentium corrupti similique reiciendis illo? Explicabo?</p>
      <p>Quis eligendi, delectus ratione voluptas consectetur inventore, amet quia suscipit alias officia necessitatibus voluptates exercitationem, architecto id voluptatibus hic eum. Debitis consequuntur ipsam neque voluptas harum necessitatibus, nobis laborum ab accusamus pariatur veniam quod quibusdam, iusto, commodi deleniti libero error.</p>
      <p>Dolores veritatis neque incidunt adipisci beatae voluptate, error optio accusamus, dignissimos commodi ipsum ipsam illum animi? Beatae natus at debitis quis perspiciatis sit ipsa aliquam commodi neque, ipsam inventore, incidunt minus itaque! Provident dicta enim laudantium ratione temporibus corrupti placeat.</p>
      <p>Distinctio atque minus voluptas in non asperiores? Modi corrupti facilis culpa fuga dolorem quos. Sequi modi a ipsa tempore soluta quia ipsum molestias reiciendis corporis iusto! Nemo pariatur repellat expedita et corrupti cum nesciunt. Aut at illo veniam quibusdam blanditiis.</p>
      <p>Quo, earum. Quam officiis nihil temporibus voluptas tempore dolorum minus quibusdam dolorem dolore nobis eveniet repellat laboriosam a, magni modi ex illum esse nisi. Eos distinctio, cum suscipit provident a nostrum, numquam ratione voluptate minima, magni repellat nisi dolorum error.</p>
      <p>Quidem a atque quae voluptatibus, aliquid ex impedit, totam aut adipisci, quo ut fugit explicabo! Asperiores odit expedita molestias magni nemo recusandae deleniti saepe soluta minus ab provident eos aliquid ducimus, perferendis culpa sequi, fuga totam corporis vero quisquam laborum?</p>
      <p>Eius provident nam sunt magnam assumenda incidunt molestias nemo ad architecto quod, non eos a in illo? Dolores praesentium possimus excepturi repellat tempore exercitationem, quod vel, necessitatibus quasi enim quae consectetur autem culpa obcaecati earum optio natus dignissimos, quis unde.</p>
      <p>Laborum, quam vero ex mollitia vel accusamus ipsum voluptas molestias doloribus? Vero dolorum libero veniam eius ea natus consequuntur nemo. Ea veniam nostrum sit delectus vitae repellendus magnam aspernatur! Debitis ratione placeat molestiae quidem nesciunt rem alias consequuntur laborum neque!</p>
      <p>Magnam quisquam, quidem quos sapiente, fugiat deserunt ipsa architecto obcaecati enim beatae sit aliquid omnis, commodi ut vel ratione voluptate animi incidunt. Inventore tenetur magnam non quod vero earum harum quibusdam itaque temporibus laboriosam? Perferendis ipsum aliquid praesentium adipisci blanditiis.</p>
      <p>Consequatur iusto nihil sunt optio animi eveniet molestias doloribus doloremque voluptates laboriosam placeat totam a, odio soluta dolores, tempore expedita inventore eaque deserunt qui est possimus maxime quam magni! Debitis dolorum non illo vero. Alias blanditiis iste voluptatibus quisquam quasi?</p>
      <p>Voluptatibus atque quam porro quia, laboriosam dolores veritatis vitae optio maxime natus. Quas sequi, eveniet rerum praesentium hic possimus qui asperiores excepturi provident exercitationem non consequuntur vel saepe optio blanditiis molestiae aut harum? Aliquam non dignissimos numquam dolorum nisi nobis.</p>
      <p>Nobis ducimus, nisi quaerat nulla magnam libero sint ad illum vero, facilis molestias sunt minima ipsum eaque totam harum voluptate impedit tenetur aut. Recusandae quis ex accusantium libero assumenda explicabo consectetur facere dolore architecto, mollitia itaque, esse suscipit sint vitae?</p>
      <p>Dignissimos inventore quisquam voluptatibus cum dolorum corporis corrupti quos porro tenetur asperiores? Blanditiis dolor architecto expedita molestiae amet alias accusantium odit beatae fuga laboriosam quam qui esse aliquid in, illo nobis cumque mollitia odio rerum vel voluptatum quidem inventore? Quibusdam.</p>
      <p>Possimus vitae vel saepe non? Veniam, sapiente doloribus sunt fuga accusamus magnam adipisci quidem nemo esse neque? Neque suscipit ducimus commodi aliquam. Repellat in officiis beatae repellendus natus numquam. Quae soluta vitae ex, architecto repellendus ipsum voluptatum in maiores! Dolore!</p>
      <p>Praesentium non, pariatur esse cumque laboriosam iusto a, dicta repellat, natus quos fugiat inventore fuga vitae. Necessitatibus ducimus, repellendus hic numquam, deserunt nesciunt ullam magni voluptatem voluptate molestias ipsum error atque impedit aperiam debitis illum omnis odit, qui temporibus fugiat.</p>
      <p>At vel molestiae reiciendis sunt, illum placeat omnis vitae molestias. Earum, quaerat minima. Repellendus sit fuga nisi delectus ab laborum vero mollitia corporis voluptate adipisci veritatis ipsum amet ducimus dolor eius aliquam quidem, obcaecati magni reiciendis. Ea veniam optio placeat?</p>
      <p>Recusandae neque laudantium voluptatum nemo temporibus sed voluptate adipisci animi beatae amet nihil commodi, eveniet eos? Animi saepe praesentium, odit numquam qui eveniet porro explicabo dolorem perferendis alias repellat laudantium sed! Expedita commodi asperiores, eligendi velit eum repellat dolores non.</p>
      <p>Illum porro repellendus dolorum beatae in consequatur, odit ducimus laboriosam ut voluptas maiores esse numquam. Molestias, nulla mollitia! Hic, amet asperiores eos totam incidunt nobis facere laborum cumque molestias voluptate qui ex. Repellendus sunt reprehenderit nam, animi et voluptatibus qui.</p>
      <p>Doloremque ratione assumenda error repellendus nobis similique veniam saepe! Corporis ex sunt enim rem error, dicta ipsam quos iure asperiores perferendis suscipit recusandae dolorem quia iusto quod ut, cupiditate sequi explicabo aliquid, esse consequuntur. Nobis eum suscipit ad cumque quaerat.</p>
      <p>Numquam ea ipsum iste itaque incidunt odit iure odio accusamus? Sunt fugit culpa soluta, accusamus rerum laborum temporibus dolore similique deserunt enim praesentium. Nostrum earum, est odio a unde nam debitis culpa dolores quaerat ipsam neque ab quod quisquam dolor!</p>
      <p>Quisquam, facilis atque explicabo omnis perferendis quae aliquid odio sint consequatur rerum quibusdam exercitationem recusandae nobis nemo id dolore animi itaque beatae eligendi? Veritatis ea eaque voluptate blanditiis suscipit alias placeat, distinctio beatae est officiis, nemo cumque aliquid recusandae necessitatibus.</p>
      <p>Tempora earum dolor necessitatibus distinctio at recusandae ducimus quod ullam repellendus pariatur dolore eveniet, reprehenderit nesciunt iure, esse laudantium enim fugit rem sequi delectus vel ipsum nihil est? Laudantium nostrum doloribus obcaecati ad adipisci, omnis aliquid suscipit commodi sequi neque.</p>
      <p>Rerum harum facilis ratione molestias adipisci, nulla explicabo rem inventore commodi enim cupiditate modi tenetur fugit ad nisi possimus provident fuga obcaecati veniam sequi aut libero sunt repudiandae perspiciatis? Officia optio rem cumque velit quis illum nulla quam sequi neque!</p>
      <p>Officiis expedita rerum fugit accusamus aspernatur iusto perspiciatis mollitia aut, cupiditate quod doloribus voluptatem animi nulla eaque voluptate, aliquam omnis quibusdam iste culpa delectus eligendi ipsa ad? Id quidem totam modi, enim recusandae numquam quibusdam voluptatum magni quas vel veniam?</p>
      <p>Eligendi reprehenderit autem iure vel provident facilis nulla ducimus explicabo alias excepturi aliquid nam et, quibusdam ratione quae saepe nobis sequi? Sequi corporis deleniti officiis excepturi sunt? Dolorem perferendis voluptatem ipsam nesciunt, aperiam asperiores nulla minus libero eligendi at perspiciatis!</p>
      <p>Corporis itaque nihil mollitia atque architecto suscipit, sequi iure pariatur, at quos ad exercitationem accusantium officiis cum animi enim id similique necessitatibus ipsam fugiat distinctio dolores natus illo. Eos, repudiandae. Numquam eaque error labore nobis, possimus dolorem architecto aut reiciendis.</p>
      <p>Similique libero, quis iste impedit sed cupiditate veritatis recusandae reprehenderit optio temporibus nihil necessitatibus, facere officiis accusantium! Quos perferendis modi, laboriosam consectetur quaerat nemo repudiandae blanditiis dolore fugiat repellat, nisi suscipit id a pariatur iusto molestias magnam commodi dolorem sapiente?</p>
      <p>Animi ad voluptates nostrum labore magni dolorem commodi, porro, asperiores optio numquam eligendi. Dolor, quam impedit delectus ex blanditiis laboriosam sed laudantium incidunt in quibusdam ad corporis minima explicabo voluptatem aperiam repellendus dolores illo voluptatibus laborum? Quasi vel perspiciatis odit.</p>
      <p>Aliquam dolor commodi neque ratione laudantium enim nisi id, cumque laborum? Quod odio reiciendis ad deleniti et temporibus ipsam beatae, dicta omnis deserunt minus velit fugit nulla tenetur suscipit autem eligendi quasi voluptate quisquam? Ex dolorem eveniet amet hic consequatur?</p>
      <p>Consequatur ad, beatae et eum rerum distinctio ea aliquam repellendus facilis, ratione culpa repudiandae consectetur consequuntur! Animi in labore fugiat, voluptatibus distinctio doloribus cupiditate eligendi quas vel, soluta laudantium ipsa dolorem! Dicta accusantium aspernatur aliquam eveniet omnis dolorem recusandae repellendus?</p>
      <p>Sint ut modi temporibus dolore ex unde dolorem debitis similique voluptas facilis perspiciatis id, eaque repellat sunt doloremque! Esse quos a consectetur debitis, nisi ab vel eligendi et voluptatum optio exercitationem neque magnam suscipit itaque praesentium sit temporibus omnis. Sapiente?</p>
      <p>Iure assumenda, quibusdam eveniet magnam aliquid nobis officiis est veritatis commodi autem, eius, unde recusandae. Praesentium, nam quam fugit dolore deleniti fugiat. Saepe commodi ab voluptas! Tempora dicta enim, labore quas ab sapiente, nisi similique sit unde incidunt, modi impedit.</p>
      <p>Illum labore totam minima aspernatur doloribus qui, eveniet dolorem sed dolores laborum. Eligendi delectus ut debitis iure repellendus earum expedita. Corporis quo quasi quod nihil odit hic aperiam, vero veritatis dignissimos cumque sed commodi saepe libero autem necessitatibus odio quam?</p>
      <p>Provident aut velit dignissimos cupiditate sunt consequuntur quibusdam eveniet adipisci non minima necessitatibus, nemo ut culpa, suscipit beatae. Commodi, ea et dolor nisi dolore tempora cum a earum ipsum recusandae sint itaque aspernatur veritatis rem vel culpa. Reprehenderit, distinctio dolores.</p>
      <p>Nihil dolores saepe debitis dolorem nesciunt. Quisquam, nesciunt explicabo commodi necessitatibus perferendis odit et laboriosam veritatis, dolorem asperiores, ut adipisci aliquid accusantium. Aliquid tempora eaque repellendus tempore alias placeat voluptatibus aperiam reiciendis adipisci quod vitae, laudantium eum, quaerat nulla assumenda?</p>
      <p>Tenetur, rem quos? Facilis ut, eum explicabo ipsa voluptas illo. Vel placeat quibusdam iure reprehenderit modi accusantium autem cum assumenda totam. Cupiditate consequatur, quod quis dicta necessitatibus maiores pariatur et! Animi quo molestias laudantium amet blanditiis eaque dolorum vitae sunt!</p>
      <p>Omnis dignissimos voluptatem sit ea, dolorum modi sunt accusamus officiis ullam adipisci? Quam, esse nemo. Ad, molestias unde distinctio molestiae rem veritatis eos laboriosam minima omnis sunt fugiat magni dolore accusantium quisquam sed accusamus. Quisquam libero mollitia possimus doloremque deleniti!</p>
      <p>Molestias explicabo quas illum nostrum commodi nihil pariatur, eaque laudantium eum modi cupiditate earum veniam saepe totam illo dolorem, officia nemo dignissimos. Est consequatur ad tempore! Libero, praesentium laborum culpa necessitatibus corporis beatae eos nesciunt repudiandae quos possimus quo ad.</p>
      <p>Ab nam quis laborum voluptas provident quod laudantium ex hic modi rerum, molestiae corrupti adipisci omnis minus error cupiditate. Atque quidem ipsa praesentium eveniet nostrum aperiam aliquam ducimus vel ullam asperiores, facere quo odio debitis, recusandae obcaecati cupiditate consequatur voluptatum!</p>
      <p>Obcaecati fuga at error sint nemo cum quae suscipit necessitatibus nobis. Dicta quos quisquam nam! Nobis laudantium placeat ad, veniam numquam nostrum error corrupti consectetur, eveniet mollitia accusantium dolorum deserunt! Error veniam illum vitae maxime velit provident facilis nobis ratione?</p>
      <p>Tempore numquam quisquam obcaecati, eveniet reprehenderit, illum exercitationem fugit temporibus excepturi fugiat dolorem eligendi sint in delectus eaque, quasi eius magnam inventore odit dolores voluptatum hic quidem velit. Deserunt, labore. Sint id modi exercitationem aspernatur, reiciendis facilis omnis velit magni!</p>
      <p>Consequatur accusantium earum quis nihil? Delectus temporibus velit ipsam quaerat similique voluptatem deserunt dignissimos vero incidunt cupiditate, cumque obcaecati corporis tempora blanditiis provident accusantium sint accusamus molestias deleniti dolorem, nobis soluta eos eligendi impedit? Vitae veritatis et eum ut rem?</p>
      <p>Eligendi, quis quibusdam. Soluta repellat obcaecati doloremque libero ut assumenda autem maxime, ullam cumque? Consequatur deleniti repellendus ipsum. Qui suscipit nesciunt unde consequuntur quo quam, omnis deleniti quae enim reprehenderit natus consectetur cum maiores dolorum, rerum laudantium earum error explicabo.</p>
      <p>Libero repellendus, molestiae nihil itaque recusandae, esse officia doloremque qui omnis expedita velit nostrum. Exercitationem deserunt voluptates nobis, minus, quod obcaecati vitae maiores blanditiis animi et nemo dolores doloremque voluptatum porro distinctio atque dignissimos perspiciatis quis nesciunt ratione enim? Tenetur.</p>
      <p>Consectetur ea magnam quod commodi similique architecto ut aliquid, eius aspernatur vitae maxime ad impedit quos ipsum porro debitis cumque enim facere, magni nemo culpa! Vitae a accusamus cupiditate fugit quis impedit asperiores quae, natus ipsum expedita consequuntur saepe alias.</p>
      <p>Rem explicabo modi incidunt ullam asperiores provident distinctio, odit quod facere velit. Fuga magnam doloremque, similique impedit enim quae praesentium. Saepe, quos facilis recusandae eligendi illum quod sed veniam, possimus nostrum pariatur quisquam accusantium! Eum odit pariatur tempora porro eius?</p>
      <p>Non facilis at nostrum delectus vitae deserunt commodi aliquid, maiores hic cum nam doloribus error temporibus voluptatem adipisci ratione! Nam odit ratione, id illum facilis unde, placeat corporis vel excepturi accusantium rerum soluta? Quisquam consectetur, explicabo quae cum deleniti doloribus.</p>
      <p>Commodi dolorem minus repellat, eveniet culpa reprehenderit beatae quas reiciendis mollitia consectetur illo alias consequuntur corporis, voluptatem ipsum cupiditate voluptas incidunt deserunt adipisci eaque iure similique! Odio distinctio cum animi dolorem dicta aliquam natus maiores, enim voluptates nihil voluptas deserunt.</p>
      <p>Aut voluptates velit minus, quas sunt inventore nobis consectetur, pariatur amet, tempore assumenda error officiis dolorum ipsum incidunt dignissimos praesentium voluptatum. Esse quasi earum maiores commodi, nihil suscipit qui quidem placeat ipsam modi libero eos asperiores incidunt tempore corrupti enim?</p>
      <p>Numquam, laudantium! Commodi quo id facere, excepturi vero perspiciatis. Ipsum, sunt cupiditate. Aliquid quam, accusamus explicabo voluptatum maxime libero! Cum sit harum sunt numquam cumque porro hic consequuntur obcaecati, commodi aliquid provident blanditiis ea reiciendis beatae odit a eius deleniti.</p>
      <p>Dicta iusto quisquam enim cumque ullam deleniti voluptatibus ex commodi rerum amet? Voluptates accusamus qui, vitae dolores quae similique, atque, aliquam vero vel dolor sed dignissimos laboriosam? Dolores voluptas, distinctio possimus tempora quia cum, dignissimos velit repellendus nobis saepe illum.</p>
      <p>Iure aliquam hic illo saepe, tenetur labore quisquam numquam ab rerum ut, error dicta neque distinctio exercitationem ex debitis sed alias autem voluptatibus. Commodi repellendus animi deleniti odit officia tempore in eius minus blanditiis veniam. Modi nisi doloremque at ullam?</p>
      <p>Fugiat iste ex nobis doloremque eos necessitatibus dignissimos, ullam fugit laudantium laboriosam officia provident alias saepe! Sed possimus obcaecati tempora reprehenderit eveniet ea nesciunt deleniti omnis in temporibus cupiditate ab modi sequi assumenda repellat voluptatum rem alias, optio iusto architecto!</p>
      <p>Quia dolore provident eum, molestiae aperiam cupiditate dolor veritatis, ab quas magni est nemo quasi. Doloribus dignissimos culpa voluptatum possimus itaque tenetur, officia corrupti incidunt mollitia enim optio architecto et eligendi excepturi maxime sapiente similique saepe repudiandae quas aperiam voluptate?</p>
      <p>Reiciendis error illum voluptatem totam dolores nam perferendis fugit enim, aliquam eveniet inventore quo ab cupiditate labore, adipisci consectetur fugiat explicabo, ut incidunt quas obcaecati id sunt dicta? Beatae, possimus et tempora dolorum omnis eos odit quaerat mollitia placeat natus!</p>
      <p>Repellendus id distinctio nisi repudiandae suscipit beatae ducimus et dolorum quod eveniet sequi mollitia atque iste, facere assumenda, voluptatum quo nam nulla vero quia sunt. Consequatur magnam quidem aspernatur sed praesentium rerum vero, recusandae a? Optio possimus deserunt est laborum?</p>
    </div>
  )
}

export default Page2